server:
  port: 8083
spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/webfluxsecurity?&serverTimezone=Europe/Moscow
    username: root
    password: 12345

#  flyway:
#    url: jdbc:mysql://localhost:3306/webfluxsecurity
##    ?&serverTimezone=Europe/Moscow
#    locations: classpath:db/migration
