server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/webflux_security
    username: postgres
    password: 12345
  flyway:
    url: jdbc:postgresql://localhost:5432/webflux_security
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256


#server:
#  port: 8083
#spring:
#  r2dbc:
#    url: r2dbc:pool:mysql://localhost:3306/webfluxsecurity?&serverTimezone=Europe/Moscow
#    username: root
#    password: 12345

#  flyway:
#    url: jdbc:mysql://localhost:3306/webfluxsecurity
##    ?&serverTimezone=Europe/Moscow
#    locations: classpath:db/migration
